### PR TITLE
Fixed iOS InAppBrowser.close threading violation

### PR DESCRIPTION
**Pull request by fonov**
run code on main thread

issue https://github.com/matei-radu/react-native-in-app-browser/issues/80

### CODE REVIEW

**Comment by matei-radu** [comment]
Thanks for taking the time to work on this.

Is this change backward compatible with iOS < 13? This issue seems to be specific to iOS 13.

**Comment by fonov** [comment]
> Is this change backward compatible with iOS < 13?

yes of course

also code base already have this design

https://github.com/matei-radu/react-native-in-app-browser/blob/master/src/ios/RNInAppBrowser/RNInAppBrowser.swift#L27

>  This issue seems to be specific to iOS 13.

I do not think so, it common patter run UIKit code on main thread

**Comment by matei-radu** [comment]
Thanks for clarifying.

Then this looks good to me 😄. Over the weekend I'll make a new release.

**Comment by fonov** [comment]
cool) also a make support read mode for iOS maybe late a create another pull request 

```
diff --git a/node_modules/@matt-block/react-native-in-app-browser/ios/RNInAppBrowser/RNInAppBrowser.swift b/node_modules/@matt-block/react-native-in-app-browser/ios/RNInAppBrowser/RNInAppBrowser.swift
index 1f5745c..d95c8fb 100644
--- a/node_modules/@matt-block/react-native-in-app-browser/ios/RNInAppBrowser/RNInAppBrowser.swift
+++ b/node_modules/@matt-block/react-native-in-app-browser/ios/RNInAppBrowser/RNInAppBrowser.swift
@@ -12,6 +12,7 @@ class RNInAppBrowser: NSObject {
     private let SETTING_BARTINT = "preferredBarTintColor"
     private let SETTING_CONTROLTINT = "preferredControlTintColor"
     private let SETTING_COLLAPSEBAR = "barCollapsingEnabled"
+    private let SETTING_READERMODE = "entersReaderIfAvailable"
     private let presentedSafariVC = RCTPresentedViewController()
     
     @objc(openInApp:settings:)
@@ -21,7 +22,16 @@ class RNInAppBrowser: NSObject {
         let url = URL(string: url)!
         
         if #available(iOS 9.0, *) {
-            let safariVC = SFSafariViewController(url: url)
+            var safariVC: SFSafariViewController;
+            
+            if #available(iOS 11.0, *) {
+                let config = SFSafariViewController.Configuration()
+                config.entersReaderIfAvailable = readerModeIsEnabled(settings: settings)
+                safariVC = SFSafariViewController(url: url, configuration: config)
+            } else {
+                safariVC = SFSafariViewController(url: url, entersReaderIfAvailable: readerModeIsEnabled(settings: settings))
+            }
+            
             customize(safariView: safariVC, settings: settings)
             
             DispatchQueue.main.async { [weak self] in
@@ -55,9 +65,20 @@ class RNInAppBrowser: NSObject {
         }
     }
 
+    @available(iOS 9.0, *)
+    private func readerModeIsEnabled(settings: NSDictionary) -> Bool {
+        if settings.value(forKey: SETTING_READERMODE) != nil {
+            let readerMode = settings.value(forKey: SETTING_READERMODE) as! Bool
+            return readerMode
+        }
+        return false
+    }
+
     @objc(closeInApp)
     func closeInApp() -> Void {
-        presentedSafariVC?.dismiss(animated: true)
+        DispatchQueue.main.async {
+            self.presentedSafariVC?.dismiss(animated: true)
+        }
     }
     
     /// See [Difference requiresMainQueueSetup and dispatch_get_main_queue?](https://stackoverflow.com/a/50775641)
diff --git a/node_modules/@matt-block/react-native-in-app-browser/lib/settings.js b/node_modules/@matt-block/react-native-in-app-browser/lib/settings.js
index b342fb9..e7b3d6d 100644
--- a/node_modules/@matt-block/react-native-in-app-browser/lib/settings.js
+++ b/node_modules/@matt-block/react-native-in-app-browser/lib/settings.js
@@ -104,5 +104,8 @@ function sanitizeIOS(settings) {
     if (typeof settings.barCollapsingEnabled === "boolean") {
         sanitized.barCollapsingEnabled = settings.barCollapsingEnabled;
     }
+    if (typeof settings.entersReaderIfAvailable === "boolean") {
+        sanitized.entersReaderIfAvailable = settings.entersReaderIfAvailable;
+    }
     return sanitized;
 }
```

**Comment by matei-radu** [comment]
That would be great, thanks!

I don't have a macOS machine these days and I cannot work on iOS issues myself for the time being, so it is nice to see some progress on that from other contributors.

**Pull request merged**
